package com.morziz.network.network

const val NO_SERVER_ERROR = 0
const val GENERIC_ERROR = "SOMETHING_WENT_WRONG"
const val SSL_EXCEPTION = "SSL_EXCEPTION"
const val REQUEST_TIMED_OUT = "REQUEST_TIMED_OUT"
const val SOCKET_EXCEPTION = "SOCKET_EXCEPTION"
const val NO_INTERNET = "NO_INTERNET"
const val UNKNOWN_HOST = "UNKNOWN_HOST"
const val IO_EXCEPTION = "IO_EXCEPTION"
